### ISSUE TITLE
Promote to @hyperapp/debug

### ISSUE THREAD

**Issue by jorgebucaran** [mrozbarry/hyperapp-debug#1]
@mrozbarry Let's brainstorm together what steps we need to take to promote this package to the main org.

Here are some ideas:

1. Don't use a default export, instead export a function `debug`.
2. Don't use: ~window['hyperapp-debug']~, instead use `window.withDebug` function.
3. Add more information to usage, consider adding a screenshot, let's be creative.

**Comment by mrozbarry** [comment]
1. Not a problem.
2. Looks easily handled via [webpack#output.libraryExport](https://webpack.js.org/configuration/output/#output-libraryexport) along with some minor source changes from #1.
3. Absolutely. I'm working with a design friend to think through a smarter way to layout the debugger. Once I have that, I'll add some gifs.
